Task23_Low/Models/Article.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Task23_Advanced.Validation;

namespace Task23_Advanced.Models
{
    /// <summary>
    /// Article Model to represent articles.
    /// </summary>
    public class Article
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [ArticleDate(1999)]
        [DataType(DataType.Date)]
        [Display(Name = "Date")]
        public DateTime Date { get; set; }
        [Required]
        public string Content { get; set; }
    }
}

Task23_Low/Models/LibraryContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;

namespace Task23_Advanced.Models
{
    public class LibraryContext : DbContext
    {
        public LibraryContext() : base("LibraryContext")
        {
        }
        /// <summary>
        /// <c>GetNews()</c> method to get list of news from database
        /// </summary>
        /// <returns><c>List<News></c></returns>
        public List<News> GetNews()
        {
            var db = new LibraryContext();
            var news = db.News.ToList();
            return news;
        }
        /// <summary>
        /// <c>GetReviews()</c> method to get list of reviews from database
        /// </summary>
        /// <returns><c>List<Reviews></c></returns>
        public List<Review> GetReviews()
        {
            var db = new LibraryContext();
            var reviews = db.Reviews.ToList();
            return reviews;
        }
        /// <summary>
        /// <c>GetArticles()</c> method to get list of articles from database
        /// </summary>
        /// <returns><c>List<Articles></c></returns>
        public List<Article> GetArticles()
        {
            var db = new LibraryContext();
            var articles = db.Articles.ToList();
            return articles;
        }
        public override int SaveChanges()
        {
            try
            {
                return base.SaveChanges();
            }
            catch (DbEntityValidationException ex)
            {
                string errorMessages = string.Join("; ", ex.EntityValidationErrors.SelectMany(x => x.ValidationErrors).Select(x => x.PropertyName + ": " + x.ErrorMessage));
                throw new DbEntityValidationException(errorMessages);
            }
        }
        public DbSet<Review> Reviews { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Questionnaire> Questionnaires { get; set; }
        public DbSet<Article> Articles { get; set; }
    }
}

Task23_Low/Models/News.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Task23_Advanced.Models
{
    /// <summary>
    /// News Model to represent news.
    /// </summary>
    public class News
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Title { get; set; }
        [Required]
        public string Content { get; set; }
    }
}

Task23_Low/Models/Questionnaire.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Task23_Advanced.Models
{
    /// <summary>
    /// Questionnaire Model to represent questionnaires.
    /// </summary>
    public class Questionnaire
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string FullName { get; set; }
        public string Adress { get; set; }
        public bool? Scales { get; set; }
        public bool? Horns { get; set; }
        public bool? City { get; set; }
        public bool? Work { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        public string Organisation { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string Experience { get; set; }
        public string Position { get; set; }
    }
}

Task23_Low/Models/Review.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Task23_Advanced.Validation;

namespace Task23_Advanced.Models
{
    /// <summary>
    /// Review Model to represent reviews.
    /// </summary>
    public class Review
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string AuthorName { get; set; }
        [Review(1999)]
        [DataType(DataType.Date)]
        [Display(Name = "Date")]
        public DateTime Date { get; set; }
        [Required]
        public string Content { get; set; }
    }
}

Task23_Low/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task23_Advanced.Models;

namespace Task23_Advanced.Controllers
{
    public class GuestController : Controller
    {
        // GET: Guest
        public ActionResult Index()
        {
            var db = new LibraryContext();
            return View(db.GetReviews());
        }
    }
}

Task23_Low/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task23_Advanced.Models;

namespace Task23_Advanced.Controllers
{
    public class HomeController : Controller
    {
        // GET: Main
        public ActionResult Index()
        {
            var db = new LibraryContext();
            return View(db.GetNews());
        }
       
    }
}

Task23_Low/Controllers/MainController.cs
using System.Web.Mvc;
using Task23_Advanced.Models;

namespace Task23_Advanced.Controllers
{
    public class MainController : Controller
    {
        // GET: Main
        public ActionResult Index()
        {
            var db = new LibraryContext();
            return View(db.GetArticles());
        }
    }
}

Task23_Low/Controllers/QuestionnaireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task23_Advanced.Controllers
{
    public class QuestionnaireController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Scales = false;
            ViewBag.Horns = false;
            ViewBag.City = false;
            ViewBag.Works = false;
            return View();
        }
        [HttpPost]
        public ActionResult UserPassedData(FormCollection form)
        {
            ViewBag.TextReturn = "Your input fullname: "+ form["Text"];
            ViewBag.AdressReturn = "Your input adress: " + form["Adress"];
            ViewBag.ScalesReturn = "You do not have scales";
            ViewBag.HornsReturn = "You do not have horns";
            ViewBag.RegionReturn = "Your input region: " + form["Region"];
            ViewBag.OrganisationReturn = "Your input organisation: " + form["Organisation"];
            ViewBag.EmailReturn = "Your input email: " + form["Email"];
            if (Convert.ToBoolean(form["Check-box-scales"].Split(',')[0])) 
            {
                ViewBag.ScalesReturn = "You have scales";
            }
            if (Convert.ToBoolean(form["Check-box-horns"].Split(',')[0]))
            {
                ViewBag.HornsReturn = "You have horns";
            }
            ViewBag.CityReturn = "You did not checked city";
                if (form["Check-box-city"]!=null && Convert.ToBoolean(form["Check-box-city"].Split(',')[0]))
                {
                    ViewBag.CityReturn = "You checked city";
                }
            ViewBag.WorkReturn = "You did not checked work";
            if (form["Check-box-work"] != null && Convert.ToBoolean(form["Check-box-work"].Split(',')[0]))
            {
                ViewBag.WorkReturn = "You checked work";
            }
            ViewBag.CountryReturn = "Your input country: " + form["Country"];
            ViewBag.ExperienceReturn = "Your input experience : " + form["Experience"];
            ViewBag.PositionReturn = "Your input position: " + form["Position"];
            return View();
        }
    }
}

Task23_Low/Views/Guest/Index.cshtml
@model IEnumerable<Task23_Advanced.Models.Review>
@{
    Layout = "";
    ViewBag.Title = "Guest Page";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet"  href="~/Content/bootstrap.css">
 
    <link rel="stylesheet" href="~/Content/Guest.css" />
</head>
<body>
    <h1>Reviews</h1>
    <div class="container-fluid">
        @foreach (var item in Model)
        {
            <div class="review">
                <div class="author-name">@Html.DisplayFor(modelItem => item.AuthorName)</div>
                <div class="date">@Html.DisplayFor(modelItem => item.Date)</div>
                <div class="review-text">@Html.DisplayFor(modelItem => item.Content)</div>
            </div>
        }
    </div>

        <form style="background-color:darkgray;">
            <h1 style="font-size:35px;font-weight:600;font-style:italic;">Enter new review</h1>
            <label for="exampleInputEmail1" class="form-label">Enter author name</label>
            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter author name" style="font-size:30px;height:50px;width:450px;margin-left:37%;" />


            <label for="exampleInputEmail1" class="form-label">Enter review text</label>
            <textarea type="text" class="form-control" id="exampleInputPassword1" style="width:600px;height:450px; padding-bottom: 400px !important;font-size:20px;margin-left:34%;"></textarea>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

</body>
</html>

Task23_Low/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Task23_Low/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Task23_Low/Views/Home/Index.cshtml
@model IEnumerable<Task23_Advanced.Models.News>
@{
    ViewBag.Title = "Library";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <title>ViewBag.Title</title>
</head>
<body>
    <div class="container-lg d-flex flex-row bg-dark ">
        <div class="col-7">
            @foreach (var item in Model)
            {
                    <h2>@Html.DisplayFor(modelItem => item.Title)</h2>
                    @Html.DisplayFor(modelItem => item.Content)                  
            }
        </div>

        <div class="navbar navbar-dark bg-dark mx-auto" id="navbarSupportedContent">
            <ul class="navbar-nav flex-column justify-content-center ">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Main")">Main </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Guest")">Guest</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("Index", "Questionnaire")">Questionnaire</a>
                </li>
            </ul>
        </div>
    </div>
</body>
</html>

Task23_Low/Views/Home/Main.cshtml
@{
    ViewBag.Title = "Main";
}

<h2>Main</h2>

Task23_Low/Views/Main/Index.cshtml
@model IEnumerable<Task23_Advanced.Models.Article>
@{
    Layout = "";
    ViewBag.Title = "Main page of library";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="~/Content/Main.css" />

</head>
<body>
    <div class="navbar navbar-dark bg-dark ">
        <ul class="nav ">
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Index", "Main")">Main</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Index", "Guest")">Guest</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Index", "Questionnaire")">Questionnaire</a>
            </li>

        </ul>
    </div>
    @foreach (var item in Model)
    {
        <article>
            <h2> @Html.DisplayFor(modelItem => item.Name)</h2>
            <h3>@Html.DisplayFor(modelItem => item.Date)</h3>
            <p>@Html.DisplayFor(modelItem => item.Content)</p>
        </article>

    }


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/bootstrap.js")

</body>
</html>

Task23_Low/Views/Questionnaire/Index.cshtml
@{
    Layout = null;
    ViewBag.Title = "Questionnaire Page";
}
@helper MyInlineHelper(string[] words)
{
    <ol>
        @foreach (string word in words)
        {
            @word
            <li>@Html.TextBox(word)</li>
        }
    </ol>
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/Questionnaire.css")
    
</head>
<body>
    @using (Html.BeginForm("UserPassedData", "Questionnaire", FormMethod.Post))
    {
    <form class="form-container">
        <div>
            @Html.TextBox("Text", ViewBag.Text as string, new { @class = "full-name", required = "required", @placeholder = "Enter your full name", @pattern = @"[a-zA-Z'-'\s]*" })
        </div>

        @Html.TextBox("Adress", ViewBag.Adress as string, new { @class = "adress", @placeholder = "Enter your adress",@style="margin-top:20px" })
        <p>Choose your features:</p>
        <div class="checkboxes">
            @Html.CheckBox("Check-box-scales", (bool)ViewBag.Scales)
            <label for="scales">Scales</label>
            @Html.CheckBox("Check-box-horns", (bool)ViewBag.Horns)
            <label for="horns">Horns</label>
        </div>

        <div class="switches">
            <label class="switch" id="switch1">
                @Html.CheckBoxSimple("Check-box-city", new { @class = "switch-input" })

                <span class="slider"></span>
            </label>
            <label for="switch1">City</label>
            <label class="switch" id="switch2">
                @Html.CheckBoxSimple("Check-box-work", new { @class = "switch-input" ,@pattern= "[A - Za - z]" })
                <span class="slider round"></span>
            </label>
            <label for="switch1">Work</label>
        </div>
        <div class="inline-helper-container">
            @Html.MyInlineHelper(new string[] { "Email", "Organisation", "Region" })
            @MyInlineHelper(new string[] { "Country", "Experience", "Position" })
        </div>
        <input type="submit" name="Button" value="SUBMIT" />
    </form>
    }
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/bootstrap.js")
</body>
</html>

Task23_Low/Views/Questionnaire/UserPassedData.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UserPassedData</title>
</head>
<body>
    <div>
        <div>@ViewBag.TextReturn</div>
        <div>@ViewBag.AdressReturn</div>
        <div>@ViewBag.ScalesReturn</div>
        <div>@ViewBag.HornsReturn</div>
        <div>@ViewBag.CityReturn</div>
        <div>@ViewBag.WorkReturn</div>
        <div>@ViewBag.RegionReturn</div>
        <div>@ViewBag.OrganisationReturn</div>
        <div>@ViewBag.EmailReturn</div>
        <div>@ViewBag.CountryReturn</div>
        <div>@ViewBag.ExperienceReturn</div>
        <div>@ViewBag.PositionReturn</div>
    </div>
</body>
</html>

Task23_Low/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/Site.css" />
</head>
<body>
    <div class="title" style="width:100%">
        <img class="library_icon" src="~/icons/library-building.png" alt="library_img" align="left" />
        <h1>@ViewBag.Title</h1>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer class="col-lg-12 bg-dark" style="margin-top:40px">
        <div class="d-flex flex-column align-items-center justify-content-center">
            <span style="color:aliceblue">Bohdan Marii </span>
            <span style="color:aliceblue">bohdan.marii.ki.2018@lpnu.ua </span>
            <span style="color:aliceblue"> © 2021 All Rights Reserved </span>
            <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
        </div>
    </footer>

    @Scripts.Render("~/Scripts/script.js")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/bootstrap.js")
    @RenderSection("scripts", required: false)
</body>
</html>